export const STATUS_LIST = {
	IN_CONSIDER: 'IN_CONSIDER',
	APPROACH: 'APPROACH',
	NOT_APPROACH: 'NOT_APPROACH',
	INTERVIEW_NOTIFICATION_IS_SENT: 'INTERVIEW_NOTIFICATION_IS_SENT',
	INTERVIEWING: 'INTERVIEWING',
	INTERVIEWED: 'INTERVIEWED',
	INTERVIEW_SUCCESS: 'INTERVIEW_SUCCESS',
	INTERVIEW_DENIED: 'INTERVIEW_DENIED',
	PAID: 'PAID',
	NOT_PAID: 'NOT_PAID'
}

export const hours = ['9:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00'];